Repository dnd-side-project/dnd-8th-2-backend, pull requests merged in 2023-02, with the labels that each got.

#2 이슈 템플릿, PR 템플릿 추가
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📝 documentation

#4 Entity 추가 및 설정
  src/main/java/com/dnd/reetplace/ReetPlaceApplication.java
  src/main/java/com/dnd/reetplace/app/domain/Answer.java
  src/main/java/com/dnd/reetplace/app/domain/Member.java
  src/main/java/com/dnd/reetplace/app/domain/Question.java
  src/main/java/com/dnd/reetplace/app/domain/S3File.java
  src/main/java/com/dnd/reetplace/app/domain/Survey.java
  src/main/java/com/dnd/reetplace/app/domain/bookmark/BookMarkRelLink.java
  src/main/java/com/dnd/reetplace/app/domain/bookmark/Bookmark.java
  src/main/java/com/dnd/reetplace/app/domain/common/BaseTimeEntity.java
  src/main/java/com/dnd/reetplace/app/domain/place/Address.java
  src/main/java/com/dnd/reetplace/app/domain/place/Place.java
  src/main/java/com/dnd/reetplace/app/domain/place/Point.java
  src/main/java/com/dnd/reetplace/app/type/BookmarkType.java
  src/main/java/com/dnd/reetplace/app/type/LoginType.java
  src/main/java/com/dnd/reetplace/app/type/PlaceCategoryGroupCode.java
  src/main/java/com/dnd/reetplace/app/type/SurveyType.java
  src/test/java/com/dnd/reetplace/app/domain/place/AddressTest.java
Labels: 💫 feature

#7 Exception 처리 환경 구축
  src/main/java/com/dnd/reetplace/app/dto/common/ErrorResponse.java
  src/main/java/com/dnd/reetplace/global/exception/CustomException.java
  src/main/java/com/dnd/reetplace/global/exception/CustomExceptionType.java
  src/main/java/com/dnd/reetplace/global/exception/GlobalExceptionHandler.java
  src/main/java/com/dnd/reetplace/global/exception/GlobalExceptionType.java
  src/main/java/com/dnd/reetplace/global/exception/common/BadRequestException.java
  src/main/java/com/dnd/reetplace/global/exception/common/ConflictException.java
  src/main/java/com/dnd/reetplace/global/exception/common/ForbiddenException.java
  src/main/java/com/dnd/reetplace/global/exception/common/NotFoundException.java
  src/main/java/com/dnd/reetplace/global/exception/common/UnauthorizedException.java
Labels: 💫 feature

#9 Develop CI, Main CI/CD 설정 및 Nginx 무중단 배포 설정
  .github/workflows/develop.yml
  .github/workflows/main.yml
  appspec.yml
  scripts/health_check.sh
  scripts/run_new_was.sh
  scripts/switch.sh
  src/main/java/com/dnd/reetplace/app/config/SecurityConfig.java
  src/main/java/com/dnd/reetplace/app/controller/HealthController.java
Labels: 🗃 infra

#12 Logging 환경 구축
  src/main/java/com/dnd/reetplace/global/exception/GlobalExceptionHandler.java
  src/main/java/com/dnd/reetplace/global/exception/GlobalExceptionType.java
  src/main/java/com/dnd/reetplace/global/log/LogUtils.java
  src/main/java/com/dnd/reetplace/global/log/aop/LogTrace.java
  src/main/java/com/dnd/reetplace/global/log/aop/LogTraceAspect.java
  src/main/java/com/dnd/reetplace/global/log/aop/Pointcuts.java
  src/main/java/com/dnd/reetplace/global/log/aop/TraceId.java
  src/main/java/com/dnd/reetplace/global/log/aop/TraceStatus.java
  src/main/java/com/dnd/reetplace/global/log/filter/LogApiInfoFilter.java
  src/main/java/com/dnd/reetplace/global/log/filter/RequestWrapper.java
  src/main/java/com/dnd/reetplace/global/log/filter/ResponseWrapper.java
Labels: 💫 feature

#13 도메인 연결 및 https 설정
  scripts/health_check.sh
  src/main/java/com/dnd/reetplace/app/controller/HealthController.java
Labels: 🗃 infra

#17 Swagger 의존성 추가 및 설정
  build.gradle
  src/main/java/com/dnd/reetplace/app/config/SecurityConfig.java
  src/main/java/com/dnd/reetplace/app/config/SwaggerConfig.java
  src/main/java/com/dnd/reetplace/global/log/LogUtils.java
  src/main/java/com/dnd/reetplace/global/log/filter/LogApiInfoFilter.java
  src/main/resources/application.yml
Labels: ⚙️ chore, 💫 feature

#16 Actuator에서 제공하는 health check 엔드포인트 사용 변경
  scripts/health_check.sh
  src/main/java/com/dnd/reetplace/app/controller/HealthController.java
Labels: ♻️ refactor

#19 Error 응답 데이터 변경 - Validation Exception
  src/main/java/com/dnd/reetplace/global/exception/GlobalExceptionHandler.java
  src/main/java/com/dnd/reetplace/global/exception/GlobalExceptionType.java
  src/main/java/com/dnd/reetplace/global/exception/ValidationErrorDetails.java
  src/main/java/com/dnd/reetplace/global/exception/ValidationErrorResponse.java
  src/main/java/com/dnd/reetplace/global/exception/type/ValidationErrorCode.java
  src/main/java/com/dnd/reetplace/global/exception/util/ViolationMessageResolver.java
Labels: 💫 feature

#21 Exception 처리 환경 구축 - Spring MVC default exception 처리, Validation error response 변경
  src/main/java/com/dnd/reetplace/app/dto/common/ErrorResponse.java
  src/main/java/com/dnd/reetplace/app/dto/exception/ErrorResponse.java
  src/main/java/com/dnd/reetplace/global/exception/CustomException.java
  src/main/java/com/dnd/reetplace/global/exception/CustomExceptionType.java
  src/main/java/com/dnd/reetplace/global/exception/ExceptionType.java
  src/main/java/com/dnd/reetplace/global/exception/GlobalExceptionHandler.java
  src/main/java/com/dnd/reetplace/global/exception/GlobalExceptionType.java
  src/main/java/com/dnd/reetplace/global/exception/ValidationErrorDetails.java
  src/main/java/com/dnd/reetplace/global/exception/ValidationErrorResponse.java
  src/main/java/com/dnd/reetplace/global/exception/type/ValidationErrorCode.java
  src/main/java/com/dnd/reetplace/global/exception/util/ViolationMessageResolver.java
  src/main/java/com/dnd/reetplace/global/log/filter/LogApiInfoFilter.java
Labels: 💫 feature

#20 Jacoco 설정, Redis 적용 (Refresh token) 및 카카오 로그인 구현
  build.gradle
  lombok.config
  src/main/java/com/dnd/reetplace/app/config/EmbeddedRedisConfig.java
  src/main/java/com/dnd/reetplace/app/config/RedisRepositoryConfig.java
  src/main/java/com/dnd/reetplace/app/config/SecurityConfig.java
  src/main/java/com/dnd/reetplace/app/controller/AuthController.java
  src/main/java/com/dnd/reetplace/app/dto/auth/RefreshTokenDto.java
  src/main/java/com/dnd/reetplace/app/dto/auth/response/KakaoProfileResponse.java
  src/main/java/com/dnd/reetplace/app/dto/auth/response/LoginResponse.java
  src/main/java/com/dnd/reetplace/app/dto/auth/response/TokenResponse.java
  src/main/java/com/dnd/reetplace/app/dto/member/MemberDto.java
  src/main/java/com/dnd/reetplace/app/repository/MemberRepository.java
  src/main/java/com/dnd/reetplace/app/repository/RefreshTokenRedisRepository.java
  src/main/java/com/dnd/reetplace/app/service/OAuth2HttpRequestService.java
  src/main/java/com/dnd/reetplace/app/service/OAuth2Service.java
  src/main/java/com/dnd/reetplace/app/service/RefreshTokenRedisService.java
  src/main/java/com/dnd/reetplace/app/type/RoleType.java
  src/main/java/com/dnd/reetplace/global/exception/ExceptionType.java
  src/main/java/com/dnd/reetplace/global/exception/GlobalExceptionHandler.java
  src/main/java/com/dnd/reetplace/global/exception/auth/JwtTokenEmptyUnauthorizedException.java
  src/main/java/com/dnd/reetplace/global/exception/auth/KakaoUnauthorizedException.java
  src/main/java/com/dnd/reetplace/global/exception/auth/RefreshTokenNotFoundException.java
  src/main/java/com/dnd/reetplace/global/exception/member/MemberUidNotFoundException.java
  src/main/java/com/dnd/reetplace/global/security/JwtAccessDeniedHandler.java
  src/main/java/com/dnd/reetplace/global/security/JwtAuthenticationEntryPoint.java
  src/main/java/com/dnd/reetplace/global/security/JwtAuthenticationFilter.java
  src/main/java/com/dnd/reetplace/global/security/MemberDetails.java
  src/main/java/com/dnd/reetplace/global/security/TokenProvider.java
  src/main/resources/application.yml
  src/test/java/com/dnd/reetplace/integration/app/service/RefreshTokenRedisIntegrationTest.java
  src/test/java/com/dnd/reetplace/unit/app/domain/place/AddressTest.java
Labels: ⚙️ chore, 💫 feature

#23 카카오 로그인, refresh 엔드포인트 Swagger 문서 작성
  src/main/java/com/dnd/reetplace/app/controller/AuthController.java
Labels: 📝 documentation

#32 Swagger 의존성 추가 및 설정 - Access token 관련 설정
  src/main/java/com/dnd/reetplace/app/config/SwaggerConfig.java
  src/main/java/com/dnd/reetplace/app/controller/AuthController.java
Labels: 💫 feature

#25 로그인한 사용자 정보 조회 기능 구현
  src/main/java/com/dnd/reetplace/app/controller/MemberController.java
  src/main/java/com/dnd/reetplace/app/dto/auth/response/LoginResponse.java
  src/main/java/com/dnd/reetplace/app/dto/member/response/MemberResponse.java
  src/main/java/com/dnd/reetplace/app/service/MemberService.java
  src/main/java/com/dnd/reetplace/global/exception/ExceptionType.java
  src/main/java/com/dnd/reetplace/global/exception/member/MemberIdNotFoundException.java
  src/main/java/com/dnd/reetplace/global/exception/member/MemberUidNotFoundException.java
  src/main/java/com/dnd/reetplace/global/security/JwtAuthenticationFilter.java
  src/main/java/com/dnd/reetplace/global/security/MemberDetails.java
  src/test/java/com/dnd/reetplace/integration/app/service/MemberIntegrationTest.java
  src/test/java/com/dnd/reetplace/unit/app/controller/MemberControllerTest.java
Labels: 💫 feature

#31 로그아웃 기능 구현
  src/main/java/com/dnd/reetplace/app/controller/AuthController.java
  src/main/java/com/dnd/reetplace/app/service/RefreshTokenRedisService.java
  src/test/java/com/dnd/reetplace/integration/app/service/RefreshTokenRedisIntegrationTest.java
Labels: 💫 feature
