Repository dnd-side-project/dnd-8th-2-backend, pull requests merged in 2023-03, with the labels that each got.

#33 서비스 탈퇴하기 기능 구현
  src/main/java/com/dnd/reetplace/app/controller/AuthController.java
  src/main/java/com/dnd/reetplace/app/dto/member/response/MemberResponse.java
  src/main/java/com/dnd/reetplace/app/dto/survey/SurveyDto.java
  src/main/java/com/dnd/reetplace/app/dto/survey/request/SurveyRequest.java
  src/main/java/com/dnd/reetplace/app/repository/MemberRepository.java
  src/main/java/com/dnd/reetplace/app/repository/SurveyRepository.java
  src/main/java/com/dnd/reetplace/app/service/MemberService.java
  src/main/java/com/dnd/reetplace/app/service/OAuth2HttpRequestService.java
  src/main/java/com/dnd/reetplace/app/service/OAuth2Service.java
  src/test/java/com/dnd/reetplace/integration/app/service/MemberIntegrationTest.java
Labels: 💫 feature

#38 북마크 생성 API 구현
  src/main/java/com/dnd/reetplace/app/controller/BookmarkController.java
  src/main/java/com/dnd/reetplace/app/domain/bookmark/BookMarkRelLink.java
  src/main/java/com/dnd/reetplace/app/domain/bookmark/Bookmark.java
  src/main/java/com/dnd/reetplace/app/domain/place/Place.java
  src/main/java/com/dnd/reetplace/app/domain/place/PlaceCategory.java
  src/main/java/com/dnd/reetplace/app/domain/place/PlaceSubCategory.java
  src/main/java/com/dnd/reetplace/app/domain/place/Point.java
  src/main/java/com/dnd/reetplace/app/dto/bookmark/BookmarkDto.java
  src/main/java/com/dnd/reetplace/app/dto/bookmark/request/BookmarkCreateRequest.java
  src/main/java/com/dnd/reetplace/app/dto/bookmark/response/BookmarkCreateResponse.java
  src/main/java/com/dnd/reetplace/app/dto/member/response/MemberResponse.java
  src/main/java/com/dnd/reetplace/app/dto/place/PlaceDto.java
  src/main/java/com/dnd/reetplace/app/dto/place/request/PlaceRequest.java
  src/main/java/com/dnd/reetplace/app/dto/place/response/PlaceResponse.java
  src/main/java/com/dnd/reetplace/app/repository/BookmarkRepository.java
  src/main/java/com/dnd/reetplace/app/repository/PlaceRepository.java
  src/main/java/com/dnd/reetplace/app/service/BookmarkService.java
  src/main/java/com/dnd/reetplace/global/exception/ExceptionType.java
  src/main/java/com/dnd/reetplace/global/exception/place/PlaceKakaoPidNotFoundException.java
  src/test/java/com/dnd/reetplace/unit/app/controller/BookmarkControllerTest.java
  src/test/java/com/dnd/reetplace/unit/app/service/BookmarkServiceTest.java
Labels: 💫 feature

#41 카테고리 및 서브 카테고리 수정
  src/main/java/com/dnd/reetplace/app/controller/BookmarkController.java
  src/main/java/com/dnd/reetplace/app/domain/place/PlaceSubCategory.java
  src/main/java/com/dnd/reetplace/app/dto/place/request/PlaceRequest.java
  src/main/java/com/dnd/reetplace/app/dto/place/response/PlaceResponse.java
Labels: 📝 documentation, ♻️ refactor

#45 북마크 리스트 조회 기능 구현
  src/main/java/com/dnd/reetplace/app/controller/BookmarkController.java
  src/main/java/com/dnd/reetplace/app/dto/bookmark/response/BookmarkResponse.java
  src/main/java/com/dnd/reetplace/app/repository/BookmarkRepository.java
  src/main/java/com/dnd/reetplace/app/service/BookmarkService.java
  src/main/java/com/dnd/reetplace/app/type/BookmarkSearchSort.java
  src/main/java/com/dnd/reetplace/app/type/BookmarkSearchType.java
  src/test/java/com/dnd/reetplace/unit/app/controller/BookmarkControllerTest.java
  src/test/java/com/dnd/reetplace/unit/app/service/BookmarkServiceTest.java
Labels: 💫 feature

#46 북마크 생성 API 구현 - 검증 로직 추가
  src/main/java/com/dnd/reetplace/app/repository/BookmarkRepository.java
  src/main/java/com/dnd/reetplace/app/service/BookmarkService.java
  src/main/java/com/dnd/reetplace/global/exception/ExceptionType.java
  src/main/java/com/dnd/reetplace/global/exception/bookmark/AlreadyMarkedPlaceException.java
  src/test/java/com/dnd/reetplace/unit/app/service/BookmarkServiceTest.java
Labels: 💫 feature

#48 장소목록조회 - 릿플인기 구현 및 Swagger CORS 설정
  build.gradle
  src/main/java/com/dnd/reetplace/app/config/SwaggerConfig.java
  src/main/java/com/dnd/reetplace/app/domain/place/Address.java
  src/main/java/com/dnd/reetplace/app/domain/place/PlaceCategory.java
  src/main/java/com/dnd/reetplace/app/domain/place/PlaceSubCategory.java
  src/main/java/com/dnd/reetplace/app/dto/place/request/PlaceGetListRequest.java
  src/main/java/com/dnd/reetplace/app/dto/place/response/KakaoPlaceResponse.java
  src/main/java/com/dnd/reetplace/app/repository/PlaceRepository.java
  src/main/java/com/dnd/reetplace/app/repository/PlaceRepositoryCustom.java
  src/main/java/com/dnd/reetplace/app/repository/PlaceRepositoryCustomImpl.java
  src/main/java/com/dnd/reetplace/app/service/PlaceService.java
Labels: 📝 documentation, 💫 feature

#54 애플 로그인 구현
  src/main/java/com/dnd/reetplace/app/controller/AuthController.java
  src/main/java/com/dnd/reetplace/app/dto/auth/response/ApplePublicKeyResponse.java
  src/main/java/com/dnd/reetplace/app/service/OAuth2HttpRequestService.java
  src/main/java/com/dnd/reetplace/app/service/OAuth2Service.java
  src/main/java/com/dnd/reetplace/global/exception/ExceptionType.java
  src/main/java/com/dnd/reetplace/global/exception/auth/ApplePublicKeyNotFoundException.java
  src/main/java/com/dnd/reetplace/global/exception/auth/AppleUnauthorizedException.java
Labels: 💫 feature
