Repository dnd-side-project/dnd-8th-2-backend, pull requests merged in 2023-11, with the labels that each got.

#82 전체 북마크 간략 정보 조회 API
  src/main/java/com/dnd/reetplace/app/controller/BookmarkController.java
  src/main/java/com/dnd/reetplace/app/dto/bookmark/response/BookmarkSummaryResponse.java
  src/main/java/com/dnd/reetplace/app/dto/place/response/PlaceSummaryResponse.java
  src/main/java/com/dnd/reetplace/app/repository/BookmarkRepository.java
  src/main/java/com/dnd/reetplace/app/service/BookmarkService.java
  src/test/java/com/dnd/reetplace/unit/app/controller/BookmarkControllerTest.java
  src/test/java/com/dnd/reetplace/unit/app/service/BookmarkServiceTest.java
Labels: 💫 feature

#84 [FEAT #83] 북마크 삭제 시 204 반환
  src/main/java/com/dnd/reetplace/app/controller/BookmarkController.java
  src/test/java/com/dnd/reetplace/unit/app/controller/BookmarkControllerTest.java
Labels: ♻️ refactor

#85 [main <- develop] 변경사항 운영환경 배포
  src/main/java/com/dnd/reetplace/app/controller/BookmarkController.java
  src/main/java/com/dnd/reetplace/app/dto/bookmark/response/BookmarkSummaryResponse.java
  src/main/java/com/dnd/reetplace/app/dto/place/response/PlaceSummaryResponse.java
  src/main/java/com/dnd/reetplace/app/repository/BookmarkRepository.java
  src/main/java/com/dnd/reetplace/app/service/BookmarkService.java
  src/test/java/com/dnd/reetplace/unit/app/controller/BookmarkControllerTest.java
  src/test/java/com/dnd/reetplace/unit/app/service/BookmarkServiceTest.java
Labels: 💫 feature, ♻️ refactor
