Repository dnd-side-project/dnd-8th-2-backend, pull requests merged in 2023-12, with the labels that each got.

#89 북마크 종류별 정보(개수, 대표 이미지) 조회 API 구현
  src/main/java/com/dnd/reetplace/app/controller/BookmarkController.java
  src/main/java/com/dnd/reetplace/app/dto/bookmark/response/BookmarkTypeInformationResponse.java
  src/main/java/com/dnd/reetplace/app/repository/BookmarkRepository.java
  src/main/java/com/dnd/reetplace/app/service/BookmarkService.java
  src/main/java/com/dnd/reetplace/global/exception/ExceptionType.java
  src/main/java/com/dnd/reetplace/global/exception/bookmark/BookmarkNotFoundException.java
  src/test/java/com/dnd/reetplace/unit/app/controller/BookmarkControllerTest.java
  src/test/java/com/dnd/reetplace/unit/app/service/BookmarkServiceTest.java
Labels: 💫 feature

#90 [main <- develop]
  src/main/java/com/dnd/reetplace/app/controller/BookmarkController.java
  src/main/java/com/dnd/reetplace/app/controller/SearchController.java
  src/main/java/com/dnd/reetplace/app/domain/Search.java
  src/main/java/com/dnd/reetplace/app/dto/bookmark/response/BookmarkTypeInformationResponse.java
  src/main/java/com/dnd/reetplace/app/dto/search/SearchDto.java
  src/main/java/com/dnd/reetplace/app/dto/search/response/SearchHistoryListResponse.java
  src/main/java/com/dnd/reetplace/app/dto/search/response/SearchHistoryResponse.java
  src/main/java/com/dnd/reetplace/app/repository/BookmarkRepository.java
  src/main/java/com/dnd/reetplace/app/repository/SearchRepository.java
  src/main/java/com/dnd/reetplace/app/repository/SearchRepositoryCustom.java
  src/main/java/com/dnd/reetplace/app/repository/SearchRepositoryCustomImpl.java
  src/main/java/com/dnd/reetplace/app/service/BookmarkService.java
  src/main/java/com/dnd/reetplace/app/service/PlaceService.java
  src/main/java/com/dnd/reetplace/app/service/ScrapService.java
  src/main/java/com/dnd/reetplace/app/service/SearchService.java
  src/main/java/com/dnd/reetplace/global/exception/ExceptionType.java
  src/main/java/com/dnd/reetplace/global/exception/bookmark/BookmarkNotFoundException.java
  src/test/java/com/dnd/reetplace/integration/app/service/SearchIntegrationTest.java
  src/test/java/com/dnd/reetplace/unit/app/controller/BookmarkControllerTest.java
  src/test/java/com/dnd/reetplace/unit/app/controller/SearchControllerTest.java
  src/test/java/com/dnd/reetplace/unit/app/service/BookmarkServiceTest.java
  src/test/java/com/dnd/reetplace/unit/app/service/SearchServiceTest.java
Labels: 🗃 infra

#92 검색기록 삭제 / 카테고리 필터 수정
  src/main/java/com/dnd/reetplace/app/controller/PlaceController.java
  src/main/java/com/dnd/reetplace/app/controller/SearchController.java
  src/main/java/com/dnd/reetplace/app/domain/LikeCategory.java
  src/main/java/com/dnd/reetplace/app/dto/category/LikeCategoryDto.java
  src/main/java/com/dnd/reetplace/app/dto/category/request/LikeCategoryRequest.java
  src/main/java/com/dnd/reetplace/app/dto/category/request/LikeCategoryUpdateRequest.java
  src/main/java/com/dnd/reetplace/app/dto/place/request/PlaceGetListRequest.java
  src/main/java/com/dnd/reetplace/app/dto/place/response/KakaoPlaceSearchListResponse.java
  src/main/java/com/dnd/reetplace/app/dto/place/response/KakaoPlaceSearchResponse.java
  src/main/java/com/dnd/reetplace/app/dto/place/response/Meta.java
  src/main/java/com/dnd/reetplace/app/dto/place/response/PlaceSearchListResponse.java
  src/main/java/com/dnd/reetplace/app/dto/place/response/PlaceSearchResponse.java
  src/main/java/com/dnd/reetplace/app/dto/place/response/SameName.java
  src/main/java/com/dnd/reetplace/app/dto/search/SearchDto.java
  src/main/java/com/dnd/reetplace/app/dto/search/response/SearchHistoryResponse.java
  src/main/java/com/dnd/reetplace/app/repository/LikeCategoryRepository.java
  src/main/java/com/dnd/reetplace/app/repository/SearchRepository.java
  src/main/java/com/dnd/reetplace/app/service/KakaoHttpRequestService.java
  src/main/java/com/dnd/reetplace/app/service/PlaceService.java
  src/main/java/com/dnd/reetplace/app/service/SearchService.java
  src/main/java/com/dnd/reetplace/global/converter/LikeSubCategoryConverter.java
  src/main/java/com/dnd/reetplace/global/exception/ExceptionType.java
  src/main/java/com/dnd/reetplace/global/exception/search/SearchDeletePermissionDeniedException.java
  src/main/java/com/dnd/reetplace/global/exception/search/SearchIdNotFoundException.java
  src/main/resources/application.yml
  src/test/java/com/dnd/reetplace/integration/app/service/SearchIntegrationTest.java
  src/test/java/com/dnd/reetplace/unit/app/controller/SearchControllerTest.java
  src/test/java/com/dnd/reetplace/unit/app/service/SearchServiceTest.java
Labels: 💫 feature, ♻️ refactor

#95 [FEAT #94] 카테고리 필터 조회 구현
  src/main/java/com/dnd/reetplace/app/controller/PlaceController.java
  src/main/java/com/dnd/reetplace/app/dto/category/response/LikeCategoryResponse.java
  src/main/java/com/dnd/reetplace/app/service/PlaceService.java
Labels: 💫 feature

#96 [main <- develop] 카테고리 조회 API 구현
  src/main/java/com/dnd/reetplace/app/controller/PlaceController.java
  src/main/java/com/dnd/reetplace/app/dto/category/response/LikeCategoryResponse.java
  src/main/java/com/dnd/reetplace/app/service/PlaceService.java
Labels: 🗃 infra
