Repository dnd-side-project/dnd-8th-2-backend, pull requests merged in 2024-01, with the labels that each got.

#97 Feature/bookmark bug fix
  src/main/java/com/dnd/reetplace/app/dto/bookmark/BookmarkDto.java
  src/main/java/com/dnd/reetplace/app/dto/bookmark/response/BookmarkResponse.java
  src/main/java/com/dnd/reetplace/app/repository/BookmarkRepository.java
  src/main/java/com/dnd/reetplace/app/service/BookmarkService.java
  src/test/java/com/dnd/reetplace/unit/app/service/BookmarkServiceTest.java
Labels: 🐛 bug

#98 main <- develop
  src/main/java/com/dnd/reetplace/app/dto/bookmark/BookmarkDto.java
  src/main/java/com/dnd/reetplace/app/dto/bookmark/response/BookmarkResponse.java
  src/main/java/com/dnd/reetplace/app/repository/BookmarkRepository.java
  src/main/java/com/dnd/reetplace/app/service/BookmarkService.java
  src/test/java/com/dnd/reetplace/unit/app/service/BookmarkServiceTest.java
Labels: 🗃 infra

#100 누락 장소 카테고리 추가
  src/main/java/com/dnd/reetplace/app/domain/place/PlaceSubCategory.java
Labels: 💫 feature

#101 [main <- develop] 장소 누락 카테고리 추가
  src/main/java/com/dnd/reetplace/app/domain/place/PlaceSubCategory.java
Labels: 🗃 infra

#104 개인정보이용약관 추가
  build.gradle
  src/main/java/com/dnd/reetplace/app/config/SecurityConfig.java
  src/main/java/com/dnd/reetplace/app/controller/TermsController.java
  src/main/resources/templates/terms.html
Labels: 📝 documentation

#105 [main <- develop] 개인정보이용약관 동의 추가
  build.gradle
  src/main/java/com/dnd/reetplace/app/config/SecurityConfig.java
  src/main/java/com/dnd/reetplace/app/controller/TermsController.java
  src/main/resources/templates/terms.html
Labels: 🗃 infra

#106 [FEAT #103] 애플 로그인 client id 수정
  src/main/resources/application.yml
Labels: 🐛 bug

#107 [main <- develop] 애플 로그인 client id 수정
  src/main/resources/application.yml
Labels: 🗃 infra

#110 북마크 종류 관련 잘못 작성된 API 명세 수정
  .gitignore
  src/main/java/com/dnd/reetplace/app/controller/BookmarkController.java
  src/main/java/com/dnd/reetplace/app/dto/bookmark/request/BookmarkCreateRequest.java
  src/main/java/com/dnd/reetplace/app/dto/bookmark/request/BookmarkUpdateRequest.java
  src/main/java/com/dnd/reetplace/app/dto/bookmark/response/BookmarkResponse.java
  src/main/java/com/dnd/reetplace/app/dto/bookmark/response/BookmarkSummaryResponse.java
  src/main/java/com/dnd/reetplace/app/dto/place/response/PlaceGetResponse.java
  src/main/java/com/dnd/reetplace/app/dto/place/response/PlaceSearchResponse.java
  src/main/java/com/dnd/reetplace/app/type/BookmarkSearchType.java
Labels: 🐛 bug
